- hosts: all
  tasks:
    - name: Install apt dependencies
      apt:
        pkg:
          - python3
          - python3-pip
        update_cache: yes
        state: present
      become: yes
      register: apt_result
      retries: 3
      until: apt_result is success

    - name: Install pip dependencies 
      pip:
        name:
          - flask
          - waitress
      when: apt_result is success

    - name: Clone git repository
      git:
        repo: https://github.com/reverieline/devopscourse.git
        dest: /tmp/devopscourse

    - name: Link flask app to /srv
      file:
        src: /tmp/devopscourse/01/flaskapp
        dest: /srv/flaskapp
        state: link
      become: yes

    - name: Fetch python3 executalbe
      shell: readlink -f $(which python3)
      register: py3path

    - name: Allow python3 to listen on protected ports
      capabilities:
        path: "{{ py3path.stdout }}"
        capability: cap_net_bind_service+ep
        state: present
      become: yes
